### ISSUE TITLE
Github login on makerdevs not working

### ISSUE THREAD

**Issue by syntactica-dev** [Hudell/makerdevs.com#33]
The github login doesn't seem to work at all (been like that for a while for me now). Tried different browsers, can't get into my account to update/remove my plugins from your website.

It's also still an absolute nightmare in terms of support and data/copyright protection.

**Comment by FossilMZ** [comment]
I had a similar issue, I think there's a cookie problem between https://www.makerdevs.com/ and https://makerdevs.com/

**Comment by syntactica-dev** [comment]
So since there was no response for over 2 months while I just wanted to remove my entries and the account and with the website lacking any actual direct contact info I pretty much have to do this for everyone to see. Why should I care if the website owners obviously don't care either:

This is my official notice for the owners to remove my account and the entries from their website, otherwise I'll see myself forced to file a legal complaint.

Sorry for the serious tone, but I'm tired of getting notifications that the links aren't up to date anymore while I can't change them because of a broken login that no one seems to care fixing. 

 (And no, the above thing doesn't work. While there actually is a cookie problem with the website, which is just one of a bunch of rather concerning issues on the site, it simply creates a new account for me so my actual account is still inaccessible)

**Comment by Hudell** [comment]
Your first account didn't use github for login. I've removed the second account that was linked to github. If you still want me to remove the plugins and the original account, please send me the request by email to makerdevs@hudell.com just so I can be sure that you're really you.
